services:
  rummy:
    build: .
    container_name: zwettl-rummy
    restart: unless-stopped
    ports:
      - "3008:3000"
    environment:
      - PORT=3000
    networks:
      - npm_default

networks:
  npm_default:
    external: true
